// This file will be auto-generated by `npx supabase gen types typescript --local`
// once the Supabase project is running. For now, it's a placeholder.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
