/**
 * Book ID is a UUID generated by Yjs when a book is added.
 * This same ID is used as inventory.book_id in Supabase.
 */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isValidBookId(id: string): boolean {
  return UUID_RE.test(id);
}
